# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7d2cc1b0dd8636bc83e846307b6bf0a2852597b2d79d0f3885679f757e3a6ded189d7ba5ac4afd150634d13e0310bd111b45d17040790b13829a52cbabeb527

test:
  secret_key_base: 7d20dc9d4e16deffa2613f94ccd7d2303a0929a2ee12f35a30d8222d788a2c6a857524029f9d617900e4513b9d1001c2d653e94d75d5fbfed22feeb72b23c556

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
